# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/

stages:
  - publish

cache:
  key: modules
  paths:
    - node_modules/
 
publish:
  image:
    name: "registry.gitlab.com/cosmicac/docker/node-build"
    entrypoint: ["/start.sh"]
  stage: publish
  only:
    refs:
      - master
      - develop
  script:
    # run test
    - npm install
    - npm run build
    # Authorize npm
    - npm config set //olivaw.getthread.io:4873/:_authToken="${NPM_TOKEN}"
    - npm publish --registry olivaw.getthread.io:4873